# Exception 예외처리

## 목표

자바의 예외 처리에 대해 학습하세요.

## 학습할 것 (필수)

-   자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
-   자바가 제공하는 예외 계층 구조
-   Exception과 Error의 차이는?
-   RuntimeException과 RE가 아닌 것의 차이는?
-   커스텀한 예외 만드는 방법
---



### 자바에서 예외 처리 방법 (try, catch, throw, throws, finally)
 **try-catch**
 ```
 try {
    예외를 처리하길 원하는 실행 코드;
} catch (e1) {
    e1 예외가 발생할 경우에 실행될 코드;
} catch (e2) {
    e2 예외가 발생할 경우에 실행될 코드;
}
...
finally {
    예외 발생 여부와 상관없이 무조건 실행될 코드;
}
 ```
1. try 블록 : 기본적으로 맨 먼저 실행되는 코드로 여기에서 발생한 예외는 catch 블록에서 처리
2. catch 블록 : try 블록에서 발생한 예외 코드나 예외 객체를 인수로 전달 받아 그 처리를 담당
3. finally 블록 : 이 블록은 try 블록에서 예외가 발생하건 안 하건 맨 마지막에 무조건 실행

catch 블록과 finally 블록은 선택적인 옵션으로 반드시 사용할 필요는 없음

 예외 종류별로 catch문을 선언 했을 때 일치하는 예외 종류의 catch문을 타게됨
 ```
         try {
            // 1을 0으로 나눴으므로 예외가 발생한다.
            System.out.println(1 / 0);           
        } catch (IllegalArgumentException e) {
            System.out.println(e.getClass().getName());
            System.out.println(e.getMessage());
        } catch (ArithmeticException e) {
            System.out.println(e.getClass().getName());
            System.out.println(e.getMessage());
        } catch (NullPointerException e) {
            System.out.println(e.getClass().getName());
            System.out.println(e.getMessage());
        }

=== 
java.lang.ArithmeticException
/ by zero
```


**예외처리 메커니즘** 
1. try 블록에 도달한 프로그램의 제어는 try 블록 내의 코드를 실행
    이때 만약 예외가 발생(throw)하지 않고, finally 블록이 존재하면 프로그램의 제어는 바로 finally 블록으로 이동
2. try 블록에서 예외가 발생하면 catch 핸들러는 다음과 같은 순서로 적절한 catch 블록을 찾음
   2-1. 스택에서 try 블록과 가장 가까운 catch 블록부터 차례대로 검사
   2-2. 만약 적절한 catch 블록을 찾지 못하면, 바로 다음 바깥쪽 try 블록 다음에 위치한 catch 블록을 차례대로 검사
   2-3. 이러한 과정을 가장 바깥쪽 try 블록까지 계속 검사
   2-4. 그래도 적절한 catch 블록을 찾지 못하면, 예외는 처리되지 못함
3. 만약 적절한 catch 블록을 찾게 되면, throw 문의 피연산자는 예외 객체의 형식 매개변수로 전달
4. 모든 예외 처리가 끝나면 프로그램의 제어는 finally 블록으로 이동
5. finally 블록이 모두 처리되면, 프로그램의 제어는 예외 처리문 바로 다음으로 이동
![enter image description here](http://tcpschool.com/lectures/img_java_exception_intro.png)

**throw**
에외처리를 강제로 발생 시킬 때 사용
```
try{
	if(조건){
		throw new Exception("에러 조건입니다.");
	}
}catch(Exception e){
}
```

**throws**
메소드 선언부에 예외를 ```throws```  명령어로 선언하여 사용한다. 
implements 처럼 여러종류의 exception을 ,로 기입 가능하다.
try-catch문이 굳이 필요없다.
```
	void chectkNo (int inputNo) throws Exception{
		if(inputNo > MAX){
			throw new Excpetion("input No. is lager than MAX Value"):
		}
	}
```

**finally**
앞서 설명 했지만, 예외 발생 여부와 관계없이 항상 실행되는 부분.
**finally block 안에는 return을 넣지 않는 것이 좋다.**
-> 의도하지 않는 return이 발생 할 수 있다.
```
package week09_exception;

public class exceptionTest01 {
    public static void main(String[] args) {
        String name = "Ashe";
        System.out.println(name+" "+testMethod(name));
    }
    public static String testMethod(String str){
        try{
            System.out.println("try");
            return str;
        }catch(Exception e){
            System.out.println("exception");
            return "fail";
        }finally{
            System.out.println("finally");
            return "finally";
        }

    }
}
===
try
finally
Ashe finally
```

### 자바가 제공하는 예외 계층 구조
![enter image description here](https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https://blog.kakaocdn.net/dn/RoZlV/btqS3I0AXjN/adMoY7CeVX8YCffIlNCoH0/img.png)

**Checked Exception**
- 컴파일러가 확인 할 수 있다. -> RuntimeException 외 전부
- 해당 경우 컴파일러가 exception처리 부분을 강제하는데, 미처리 시 컴파일 에러
- 주로 외부의 영향에 의해 발생

**Unchecked Exception**
- 컴파일러가 확인 불가 -> RuntimeException이하
- 프로그램 코드에 의한 에러.
- *호출하는 쪽에서 해당 메소드 호출 시 어떤 에러가 발생 가능한 지 반드시 체크 해야 함,*

*[unchecked Exception에 대한 오해](https://github.com/ByungJun25/study/tree/main/java/whiteship-study/9week)*
>`Springframework`에서는 `Transaction`설정과 관련하여 `Unchecked Exception`에 대해 `roll-back`기능을 지원합니다. 하지만 이는 `Springframework`의 `transaction`설정이 제공하는 것이지, 순수 자바 언어에서 지원하는 것이 아닙니다. 이 기능은 `springframework`가 구현한 기능일뿐, **`java`가 제공해주는  `Unchecked Exception`은  `roll-back`  기능이 없습니다.** 따라서 이를 `java`에서 제공해준다고 알고 있지 않기를 바랍니다.
- 트랜잭션 부분(rollback)은 spring 정책으로 변경 될 수 있으니 진리는 아니다.

**예외 계층**
 - catch문을 여러 개 적용 시 특정 catch문의 계층이 다른 catch문의 계층의 상위 계층이면 하위계층 exception이 우선처리된다.
 - 아래 예제에서 IndexOutOfBoundsException이 아닌 다른 에러는 e2가 처리함.
```
import java.util.LinkedList;

public class exceptionTest02 {
    public static void main(String[] args) {
        LinkedList<String> list;
        try{
            list = new LinkedList<>();
            System.out.println(list.get(0));
        }catch(IndexOutOfBoundsException e1){
            System.out.println("catch! IndexOutOfBoundsException");
        }catch(Exception e2){
            System.out.println("catch! Exception");
        }
    }
}
===
catch! IndexOutOfBoundsException
```
순서도 중요하다.
먼저 처리하는 catch의 exception계층이 나중 처리하는 catch의 exception계층보다 낮으면 컴파일 에러
![enter image description here](https://github.com/myBabyGrand/study_JAVA_whiteship_live-study/blob/main/images/exception.png?raw=true)


### Exception과 Error의 차이는?

**오류(error)와 예외(exception)**
- 오류(error) 
	*	문법에 맞지 않아 컴파일 시 또는 프로그램이 실행 시 예상치 못한 시스템 레벨의 문제
- 예외(exception) 
	* 개발자가 구현한 코드 내에서 발생,  쓰레드에 영향, 오류 중 개발자가 예상 가능한 부분으로 exception 처리코드를 통해 핸들링 가능

### RuntimeException과 RE가 아닌 것의 차이는?
예외계층구조에서 볼 수 있듯이 RE는 Unchecked, RE가 아닌 것은 Checked
위에서 확인.

### 커스텀한 예외 만드는 방법
Exception 클래스를 상속 받아 사용자 정의 예외 클래스를 만들 수 있다.
RuntimeException과 그렇지 않는 경우 Exception 을 extends 하여 구분하여 사용 하는 것이 좋다.
```
package week09_exception;

import java.io.IOException;

public class exceptionTest06 {
    public static void main(String[] args) throws ParamNullValuePosition {
        String chapion = "Ashe";
        String position = "Juggler";
        setPostion(chapion, position);
    }
    static void setPostion(String nm, String position)throws PositionException, ParamNullValuePosition{
        if(nm== null || position == null){
            throw new ParamNullValuePosition("parameter is null");
        }

        if(nm == "Ashe"  && position != "AdCarry"){
            throw new PositionException("invalid position");
        }
        System.out.println(nm +", "+position);

    }
}
//unchecked
class PositionException extends RuntimeException{
    public PositionException (String msg){
        super(msg);
    }
}

//checked
class ParamNullValuePosition extends Exception{
    public ParamNullValuePosition (String msg){
        super(msg);
    }
}
===
Exception in thread "main" week09_exception.PositionException: invalid position
	at week09_exception.exceptionTest06.setPostion(exceptionTest06.java:17)
	at week09_exception.exceptionTest06.main(exceptionTest06.java:9)
```
사용자 정의 예외 클래스 생성 시 아래의 rule을 따르는 게 좋다.

**1. Always Provide a Benefit**

자바 표준 예외들에는 다양한 장점을 가지는 기능들이 포함되어 있다.
이미 JDK가 제공하고 있는 방대한 양의 예외들과 비교했을 때 만들고자 하는 커스텀 예외가 어떠한 장점도 제공하지 못한다면?  
커스텀 예외를 만드는 이유를 다시 생각해 볼 필요가 있다.
어떠한 장점을 제공할 수 없는 예외를 만드는 것 보다 오히려 UnsupportedOperationException이나, IllegalArgumentException과 같은 표준 예외 중 하나를 사용하는 것이 낫다.

**2. Follow the Naming Convention**

JDK가 제공하는 예외 클래스들을 보면 클래스의 이름이 모두 “Exception”으로 끝나는 것을 알 수 있다. 이러한 네이밍 규칙은 자바 생태계 전체에 사용되는 규칙이다.
즉, 만들고자 하는 커스텀 예외 클래스들도 이러한 네이밍 규칙을 따르는 것이 좋다.

**3. Provide javadoc Comments for Your Exception Class**

많은 커스텀 예외들이 어떠한 javadoc 코멘트도 없이 만들어진 경우가 있다.
기본적으로 API의 모든 클래스, 멤버변수, 생성자에 대해서 문서화 하는 것이 Best Practices이다. 잘 알겠지만 문서화되지 않은 API들은 사용하기 매우 어렵다.
예외 클래스들은 API에 크게 드러나지 않는 부분일 수 있으나 사실상 그렇지 않다. 클라이언트와 직접 관련된 메소드들 중 하나가 예외를 던지면 그 예외는 바로 예외의 일부가 된다. 그렇다는 것은 잘 만들어진 JavaDoc와 문서화가 필요하다는 뜻이다.
JavaDoc은 예외가 발생할 수도 있는 상황과 예외의 일반적인 의미를 기술한다. 목적은 다른 개발자들이 API를 이해하고 일반적인 에러 상황들을 피하도록 돕는 것이다.
```
    /**
    * The MyBusinessException wraps all checked standard Java exception and enriches them with a custom error code.
    * You can use this code to retrieve localized error messages and to link to our online documentation.
    *
    * @auther TJanssen
    */
    public class MyBusinessException extends Exception { ... }
```

**4. Provide a Constructor That Sets the Cause**

커스텀 예외를 던지기 전에 표준 예외를 Catch하는 케이스가 꽤 많다. 이 사실을 꼭 기억하도록 하자.
보통 캐치된 예외에는 제품에 발생한 오류를 분석하는데 필요한 중요한 정보가 포함되어 있다.  
예제를 보면 NumberFormatException은 에러에 대한 상세정보를 제공한다.  
MyBusinessException의 cause처럼 cause정보를 설정하지 않으면 중요한 정보를 잃을 수 있다.
```
public void wrapException(String input) throws MyBusinessException {
    try {
        // do something
    } catch (NumberFormatException e) {
        throw new MyBusinessException("A message that describes the error.", e,ErrorCode.INVALID_PORT_CONFIGURATION);
    }
}
```
### live 방송
 - https://wisdom-and-record.tistory.com/46 <- 정리 잘했다.

**MultiCatch (JDK 1.7   :arrow_up_small:)**
 -  마찬가지로 예외 클래스 간 계 구조에 유의
```
try{
	throw new (
}catch(NullPointerException | IllegalArgumentException e){
	System.out.println(e.getClass());
}
===
class java.lang.NullPointerException 
```
**try-with-resource**
 - [try-with-resource](https://www.notion.so/3565a9689f714638af34125cbb8abbe8) (JDK 1.7   :arrow_up_small:)
	* exception시 resources를 자동으로 close() 해준다
	* try-catch-finally 소스랑 비교해 보라
```
//try-catch-finally
FileOutputStream out = null;
try {
    out = new FileOutputStream("thewing.txt");
    // 생략
} catch (FileNotFoundException e) {
    e.printStackTrace();
} finally {
    if (out != null) { 
        try {
            out.close(); //close 예외가 발생할 수 있다.
        } catch(IOException e) {
                e.printStackTrace();
        }
}

//try-with-resource
try(FileOutputStream out = new FileOutputStream("thewing.txt")) { 
        //생략
} catch(IOException e){ 
    e.printStackTrace(); 
}
```

**예외 되던지기 exception re-throwing**
호출하는 메소드와 처리하는 메소드 양쪽에서 처리.
양쪽 모두에서 처리가 필요할 경우 처리
return이 있는 경우 catch문에 return이 있거나,  예외 되던지기(throw e) 를 하면됨
아래 예제에서 testMethod2
```
package week09_exception;

public class exceptionTest04 {
    public static void main(String[] args) {
        try{
            testMethod1();
        }catch(Exception e){
            System.out.println("main exception Occur!");
        }
        System.out.println("====");
        try{
            testMethod2();
        }catch(Exception e){
            System.out.println("main exception Occur!");
        }

    }
    public static void testMethod1() {
        try {
            int i=1;
            int j = i/0 ;
        }catch (Exception e){
            System.out.println("testMethod1 exception Occur!");
        }
    }
    public static void testMethod2() throws Exception {
        try {
            int i=1;
            int j = i/0 ;
        }catch (Exception e){
            System.out.println("testMethod2 exception Occur!");
            throw e;
        }
    }
}
===
testMethod1 exception Occur!
----
testMethod2 exception Occur!
main exception Occur!
```

**chained Exception**
한 예외가 다른 예외를 발생 시키는 경우
- 여러 예외를 하나의 큰 분류로 묶어서 다루기 위함
- Checked Exception을 UnChecked Exception으로 바꿀 수도 있다.
```
package week09_exception;

import java.io.IOException;

public class exceptionTest05 {
    public static void main(String[] args) {
        try{
            chinedExceptionTest(null);
        }catch (Exception e){
            System.out.println("exception occur!");
            e.printStackTrace();
        }
    }
    static void chinedExceptionTest(String fileNm){
        try{
            if(fileNm == null){
                throw new IOException("file name is null");
            }
        }catch(IOException e){
            RuntimeException runtimeException = new RuntimeException();
            runtimeException.initCause(e);
            throw runtimeException;
        }
    }
}

===
exception occur!
java.lang.RuntimeException
	at week09_exception.exceptionTest05.chinedExceptionTest(exceptionTest05.java:21)
	at week09_exception.exceptionTest05.main(exceptionTest05.java:9)
Caused by: java.io.IOException: file name is null
	at week09_exception.exceptionTest05.chinedExceptionTest(exceptionTest05.java:18)
Caused by: java.io.IOException: file name is null

	... 1 more
```

**예외처리비용**

예외처리는 처리비용이 비싸다,
try-catch로 검사, Throwable 생성자의 fillinStackTrace() 메소드가 주요한 원인.(Stack Trace 출력을 위함)
이 메소드를 오버라이딩해서 StackTrace를 최소화 해줄 순 있지만 굳이 할 필요가?

- 커스텀 예외 정리
	 * https://m.blog.naver.com/sthwin/221144722072
 - Runtime Exception 부분은 한번 흝어보고 가는 게 좋다. [https://velog.io/@youngerjesus](https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)
 - intelliJ에서 바이트 코드 보는 법을 공부해보자
	  * 컴파일 된 class는 workspace\study_JAVA_whiteship_live-study\build\classes\java\main\week02_dataType\ArrayTest.class
	  * [백선장님 Youtube : 인텔리J에서 바이트코드를 보는 방법](https://www.youtube.com/watch?v=XRmxIp8mJ-o&list=ULi3p0dQrIDNo&index=65&ab_channel=%EB%B0%B1%EA%B8%B0%EC%84%A0)

### Ref.
- [TCP School](http://tcpschool.com/java/java_exception_intro)
- [기록과지혜](https://wisdom-and-record.tistory.com/46)
- [개발자 한선우](https://yadon079.github.io/2021/java%20study%20halle/week-09), [feedback](https://yadon079.github.io/2021/java%20study%20halle/week-09-feedback)
- [youngerjesus.log](https://velog.io/@youngerjesus/%EC%9E%90%EB%B0%94-%EC%98%88%EC%99%B8-%EC%B2%98%EB%A6%AC)
- [ssonsh notion](https://www.notion.so/3565a9689f714638af34125cbb8abbe8)